modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = "${mod_description}"
authors = "${mod_authors}"
logoFile = ""

[[mixins]]
config = "mixins.duocaoliuti.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "modern_industrialization"
mandatory = true
versionRange = "[2.4.2,)"
ordering = "AFTER"
side = "BOTH"